config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products do
    resources :bids
  end
  resources :users
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#delete'
  root 'products#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bid.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: bids
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  product_id :integer
#  price      :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_bids_on_product_id  (product_id)
#  index_bids_on_user_id     (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (product_id => products.id)
#  fk_rails_...  (user_id => users.id)
#

class Bid < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/product.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: products
#
#  id             :integer          not null, primary key
#  name           :string
#  description    :string
#  user_id        :integer
#  starting_price :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#
# Indexes
#
#  index_products_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#

class Product < ApplicationRecord
  belongs_to :user
  has_many :bids

  def number_of_bidders
    bids.count
  end

  def highest_bid
    bids.map { |i | i.price }.max || '-'
  end
end

app/models/user.rb
# frozen_string_literal: true
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  hashed_password :string
#

class User < ApplicationRecord
  has_many :bids

  def authenticate(password)
    BCrypt::Password.new(self.hashed_password) == password
  end
  
  def password=(password)
    @password = password
    self.hashed_password = BCrypt::Password.create(password)
  end
  
  def password
    @password
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  before_action :check_logged_in
  
  def check_logged_in
    if session[:username].nil?
      redirect_to login_path
    end
  end

  def current_user
    User.find_by(username: session[:username])
  end
end

app/controllers/bids_controller.rb
# frozen_string_literal: true

class BidsController < ApplicationController
  def new
    @product = Product.find(params[:product_id])
    @bid = Bid.new
  end

  def create
    bid = Bid.new(bid_params)
    bid.user = current_user
    bid.product_id = params[:product_id]
    if bid.save
      redirect_to products_path
    else
      @product = Product.find(params[:product_id])
      render :new
    end
  end

  def destroy
    Bid.find(params[:id]).destroy
    redirect_to products_path
  end

  def edit
    @bid = Bid.find(params[:id])
  end

  def update
    bid = Bid.find(params[:id])

    if bid.update(bid_params)
      redirect_to products_path
    else
      render :edit
    end
  end

  private def bid_params
    params.require(:bid).permit(:price)
  end

end

app/controllers/products_controller.rb
 #frozen_string_literal: true

class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    product = Product.new(product_params)
    product.user = current_user
    if product.save
      redirect_to products_path
    else
      render :new
    end
  end

  def destroy
    Product.find(params[:id]).destroy
    redirect_to products_path
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    product = Product.find(params[:id])

    if product.update(product_params)
      redirect_to products_path
    else
      render :edit
    end
  end

  private def product_params
    params.require(:product).permit(:name, :starting_price)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :check_logged_in
  
  def new # sign in
  end

  def create
    username = params[:username]
    password = params[:password]

    user = User.find_by(username: username)
    if user.nil?
      # FAIL
      render :new
    elsif user.authenticate(password)
      # LOG IN
      session[:username] = username
      redirect_to products_path
    else
      render :new
    end
  end

  def delete # sign out
    session.delete(:username)
    redirect_to products_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  skip_before_action :check_logged_in
  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      redirect_to login_path
    else
      render :new
    end
  end

  private def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/bids_helper.rb
# frozen_string_literal: true

module BidsHelper
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/bids/index.html.erb
<h1>Bid list</h1>

app/views/bids/new.html.erb
<h1>Bid for <%= @product.user.username %>'s <%= @product.name %></h1>
<%= form_for @bid, url: product_bids_path do |f| %>
		<p>
		<%= f.label :price %>
		<%= f.text_field :price %>
		</p>
		<%= f.submit 'Bid' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Auction</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<h1>Edit Your Product</h1>

<%= form_for @product do |f| %>
		<p>
		<%= f.label :name, 'Product Name' %>
		<%= f.text_field :name %>
		</p>
		<p>
		<%= f.label :starting_price %>
		<%= f.text_field :starting_price %>
		</p>
		<%= f.submit 'Edit' %>
<% end %>

app/views/products/index.html.erb
<h1>Hi, <%= session[:username] || 'guest!' %></h1>
<%= link_to "Logout", logout_path, method: :delete %>
<h1>List of Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Owner</th>
      <th>Starting Price</th>
      <th>Highest Bid</th>
      <th>No. of Bidders</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.name, product_path(product) %></td>
        <td><%= product.user.username %></td>
        <td><%= product.starting_price %></td>
        <td><%= product.highest_bid%></td>
        <td><%= product.number_of_bidders %></td>
        <td><%= link_to 'Edit', edit_product_path(id: product.id) %></td>
        <td><%= link_to 'Delete', product_path(id: product.id), method: :delete %></td>
        <td><%= link_to 'Bid', new_product_bid_path(product_id: product.id) %></td>

      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to "New Product", new_product_path %>

app/views/products/new.html.erb
<%= form_for @product do |f| %>
		<p>
		<%= f.label :name, 'Product Name' %>
		<%= f.text_field :name %>
		</p>
		<p>
		<%= f.label :starting_price %>
		<%= f.text_field :starting_price %>
		</p>
		<%= f.submit 'Create' %>
<% end %>

app/views/products/show.html.erb
<h1>Product Details</h1>
<a href="/products">Home</a>
<ul>
		<li>Name: <%= @product.name %></li>
		<li>Owner: <%= @product.user.username %></li>
		<li>Price: <%= @product.starting_price %></li>
</ul>
<br>
<%= link_to 'Edit', edit_product_path(id: @product.id) %>
<%= link_to 'Delete', product_path(id: @product.id), method: :delete %>
						

app/views/users/new.html.erb
<h1>Create New User</h1>

<%= form_for @user do |f| %>
		<p>
		<%= f.label :username  %>
		<%= f.text_field :username %>
		</p>
		<p>
		<%= f.label :password %>
		<%= f.password_field :password %>
		</p>
		<%= f.submit 'Create' %>
<% end %>